import { useEffect, useState } from 'react';
import { Session } from '@supabase/supabase-js';
import { Auth } from './components/Auth';
import { Discover } from './components/Discover';
import { Gallery } from './components/Gallery';
import { Header, Page } from './components/Header';
import { Home } from './components/Home';
import { ProfileSetup } from './components/ProfileSetup';
import { ProfileSettings } from './components/ProfileSettings';
import { ReferenceForm } from './components/ReferenceForm';
import { Shop } from './components/Shop';
import { ArtReference, loadReferences } from './lib/references';
import { loadMyProfile, Profile } from './lib/profiles';
import { supabase } from './lib/supabase';
import { Usage, visitAndGetUsage } from './lib/usage';
import { LanguageSelect } from './components/LanguageSelect';
import { useLanguage } from './lib/language';
import { usePageTranslation } from './lib/translatePage';

export default function App() {
  const { language } = useLanguage();
  const [languageChosen, setLanguageChosen] = useState(false);
  usePageTranslation(languageChosen);
  const [session, setSession] = useState<Session | null>(null);
  const [profile, setProfile] = useState<Profile | null>(null);
  const [profileChecked, setProfileChecked] = useState(false);
  const [page, setPage] = useState<Page>('home');
  const [references, setReferences] = useState<ArtReference[]>([]);
  const [loading, setLoading] = useState(true);
  const [guest, setGuest] = useState(false);
  const [usage, setUsage] = useState<Usage>();
  useEffect(() => { supabase.auth.getSession().then(({ data }) => { setSession(data.session); setLoading(false); }); const { data } = supabase.auth.onAuthStateChange((_event, next) => { setSession(next); if (!next) setProfile(null); }); return () => data.subscription.unsubscribe(); }, []);
  useEffect(() => { if (!session) return; setGuest(false); setProfileChecked(false); Promise.all([loadMyProfile(session.user.id), loadReferences(), visitAndGetUsage()]).then(([found, items, currentUsage]) => { setProfile(found); setReferences(items); setUsage(currentUsage); setProfileChecked(true); }).catch(() => setProfileChecked(true)); }, [session]);
  if (!languageChosen) return <LanguageSelect onContinue={() => setLanguageChosen(true)}/>;
  if (loading || (session && !profileChecked)) return <div className="splash">Refri<span>.</span></div>;
  if (!session && !guest) return <div className="auth-shell"><div className="auth-intro"><div className="brand-static">Refri<span>.</span></div><h1>{language === 'en' ? <>Your ideas.<br/><em>Your characters.</em></> : <>Твои идеи.<br/><em>Твои персонажи.</em></>}</h1><p>{language === 'en' ? 'Collect references, create visuals, and discover other artists.' : 'Собирай референсы, создавай визуалы и находи других художников.'}</p></div><Auth onGuest={() => setGuest(true)} /></div>;
  if (guest) return <><Header page={page} onNavigate={setPage} onSignOut={() => { setGuest(false); setLanguageChosen(false); setPage('home'); }}/>{page === 'create' ? <ReferenceForm isGuest onCreated={() => setPage('home')} /> : <Home onCreate={() => setPage('create')} onGallery={() => undefined} onDiscover={() => undefined} />}</>;
  if (!session) return null;
  if (!profile) return <ProfileSetup userId={session.user.id} onReady={setProfile}/>;
  const navigate = (next: Page) => setPage(next);
  return <><Header page={page} username={profile.username} onNavigate={navigate} onSignOut={async () => { await supabase.auth.signOut(); setLanguageChosen(false); setPage('home'); }}/>{page === 'home' && <Home profile={profile} usage={usage} onUsageChange={async () => setUsage(await visitAndGetUsage())} onCreate={() => navigate('create')} onGallery={() => navigate('gallery')} onDiscover={() => navigate('discover')}/>} {page === 'create' && <ReferenceForm onCreated={async () => { setReferences(await loadReferences()); setUsage(await visitAndGetUsage()); navigate('gallery'); }}/>} {page === 'gallery' && <Gallery references={references} setReferences={setReferences} onCreate={() => navigate('create')} onReward={async () => setUsage(await visitAndGetUsage())}/>} {page === 'shop' && usage && <Shop usage={usage} onUpdated={async () => setUsage(await visitAndGetUsage())}/>} {page === 'discover' && <Discover/>} {page === 'profile' && <ProfileSettings profile={profile} onUpdated={setProfile}/>}</>;
}
